source 'https://rubygems.org'

gem 'github-pages', '>= 207'
gem 'html-proofer', '>= 3.18.5'
gem 'jekyll', '= 3.9.0'
gem 'jekyll-avatar', '>= 0.7.0'
gem 'bootstrap', '>= 4.1.3'
gem 'jekyll-bootstrap-sass', '>= 0.1.0'
gem 'jekyll-mentions', '>= 1.5.1'
gem 'jekyll-press', '>= 0.2.1'
gem 'jekyll-seo-tag', '>= 2.6.1'
gem 'jekyll-tidy', '>= 0.2.2'
gem 'kramdown', '>= 2.3.0'
gem 'naturally', '>= 2.2.1'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'tzinfo-data', '>= 1.2020.1'
