#!/usr/bin/env bash

# halt script on error
set -e

# Do the magic
bundle exec jekyll build
bundle exec htmlproofer ./_site --url-ignore /marlinfw.org\/news/ --only-4xx --allow-hash-href --check-favicon --check-html --log-level 1

# Check DNS
bundle exec github-pages health-check
